Repository PreMiD/Activities, pull requests merged in 2024-12, with the labels that each got.

#8910 feat(RTLplay): revamp 2.0.0 + features added
  websites/R/RTLplay/metadata.json
  websites/R/RTLplay/presence.ts
  websites/R/RTLplay/util.ts
Labels: presence update

#8927 chore(BeatLeader): format metadata
  websites/B/BeatLeader/metadata.json
Labels: presence update, repo maintenance, chore

#8920 chore(LessWrong): update assets
  websites/L/LessWrong/metadata.json
  websites/L/LessWrong/presence.ts
Labels: presence update, repo maintenance, chore

#8930 chore(RTLplay): update assets
  websites/R/RTLplay/metadata.json
  websites/R/RTLplay/util.ts
Labels: presence update, repo maintenance, chore

#8923 chore(CacaX): update metada + fixs
  websites/C/CacaX/metadata.json
  websites/C/CacaX/presence.ts
Labels: presence update

#8924 fix(Crowdin): fix some broken querySelector
  websites/C/Crowdin/metadata.json
  websites/C/Crowdin/presence.ts
Labels: presence update

#8931 chore(Zaiko): update assets
  websites/Z/Zaiko/metadata.json
  websites/Z/Zaiko/presence.ts
Labels: presence update, repo maintenance, chore

#8932 chore(CacaX): update assets
  websites/C/CacaX/metadata.json
Labels: presence update, repo maintenance, chore

#8929 feat(AniLibria): add presence
  websites/A/AniLibria/metadata.json
  websites/A/AniLibria/presence.ts
Labels: new presence

#8935 feat(1Anime): Add presence
  websites/0-9/1anime/metadata.json
  websites/0-9/1anime/presence.ts
Labels: new presence

#8925 feat(Club Penguin Journey): Add presence
  websites/C/Club Penguin Journey/metadata.json
  websites/C/Club Penguin Journey/presence.ts
Labels: new presence

#8939 chore(AniLibria): update assets
  websites/A/AniLibria/metadata.json
  websites/A/AniLibria/presence.ts
Labels: presence update, repo maintenance, chore

#8940 fix(Mycanal): Better detection + crop thumbnail
  websites/M/myCANAL/metadata.json
  websites/M/myCANAL/presence.ts
Labels: presence update

#8945 chore(1anime): update assets
  websites/0-9/1anime/metadata.json
  websites/0-9/1anime/presence.ts
Labels: presence update, repo maintenance, chore

#8938 feat(PlanetXO): Add presence
  websites/P/PlanetXO/metadata.json
  websites/P/PlanetXO/presence.ts
Labels: new presence

#8946 chore(Club Penguin Journey): update assets
  websites/C/Club Penguin Journey/metadata.json
  websites/C/Club Penguin Journey/presence.ts
Labels: presence update, repo maintenance, chore

#8949 chore(PlanetXO): update assets
  websites/M/myCANAL/metadata.json
  websites/P/PlanetXO/metadata.json
  websites/P/PlanetXO/presence.ts
Labels: presence update, repo maintenance, chore

#8951 feat(Websim): Add presence
  websites/W/Websim/metadata.json
  websites/W/Websim/presence.ts
Labels: new presence

#8954 chore(Websim): update assets
  websites/W/Websim/metadata.json
  websites/W/Websim/presence.ts
Labels: presence update, repo maintenance, chore

#8943 feat(KBHGames): Add presence
  websites/K/KBHGames/metadata.json
  websites/K/KBHGames/presence.ts
Labels: new presence

#8956 fix(Twitch): fix show pfp option
  websites/T/Twitch/metadata.json
  websites/T/Twitch/presence.ts
Labels: presence update

#8957 chore(KBHGames): update assets
  websites/K/KBHGames/metadata.json
  websites/K/KBHGames/presence.ts
Labels: presence update, repo maintenance, chore

#8968 feat(Skribbl.io): change multiLanguage setting
  websites/S/Skribbl.io/metadata.json
  websites/S/Skribbl.io/presence.ts
Labels: presence update

#8967 feat(x.com): change multiLanguage setting
  websites/X/X.com/metadata.json
  websites/X/X.com/presence.ts
Labels: presence update

#8969 feat(watch.lonelil.com): change multiLanguage setting
  websites/W/watch.lonelil.com/metadata.json
  websites/W/watch.lonelil.com/presence.ts
Labels: presence update

#8971 feat(TwitCasting): update multiLanguage setting
  websites/T/TwitCasting/metadata.json
  websites/T/TwitCasting/presence.ts
Labels: presence update

#8970 feat(Minecraft Wiki): change multiLanguage setting
  websites/M/Minecraft Wiki/metadata.json
  websites/M/Minecraft Wiki/presence.ts
Labels: presence update

#8961 fix(Club Penguin Journey): fix ClientId
  websites/C/Club Penguin Journey/metadata.json
  websites/C/Club Penguin Journey/presence.ts
Labels: presence update

#8964 fix(Genius): addressing bug where song titles are undefined
  websites/G/Genius/metadata.json
  websites/G/Genius/presence.ts
Labels: presence update

#8972 chore(Club Penguin Journey): update assets
  websites/C/Club Penguin Journey/metadata.json
Labels: presence update, repo maintenance, chore

#8975 fix(Edgenuity): fixed player detection
  websites/E/Edgenuity/metadata.json
  websites/E/Edgenuity/presence.ts
Labels: presence update

#8974 chore(Genius): update assets
  websites/G/Genius/metadata.json
Labels: presence update, repo maintenance, chore

#8980 chore: lint
  cli/bin/index.js
Labels: repo maintenance, chore

#8981 feat(StudyStream): add presence
  websites/S/StudyStream/metadata.json
  websites/S/StudyStream/presence.ts
Labels: new activity

#8959 feat(LessWrong): add button for posts and profiles, display currently viewed profile
  websites/L/LessWrong/metadata.json
  websites/L/LessWrong/presence.ts
Labels: activity update

#8982 feat(jut.su): add cover art and change activity type to watching
  websites/J/jut.su/metadata.json
  websites/J/jut.su/presence.ts
Labels: activity update

#8984 chore(LessWrong): format metadata
  websites/L/LessWrong/metadata.json
Labels: activity update, repo maintenance, chore

#8985 chore(StudyStream): update assets
  websites/S/StudyStream/metadata.json
  websites/S/StudyStream/presence.ts
Labels: activity update, repo maintenance, chore

#8987 fix(TuneIn): fix presence not working with switch stations
  websites/T/TuneIn/metadata.json
  websites/T/TuneIn/presence.ts
Labels: activity update

#9007 chore(Laftel): remove service due to duplicate in korean
  websites/L/Laftel/metadata.json
  websites/L/Laftel/presence.ts
Labels: activity deletion, repo maintenance

#8996 chore: add `pnpm dev`
  package.json
Labels: repo maintenance

#8991 feat(Sorryfield): add startTimestamp and chart (by song) list page
  websites/S/Sorryfield/metadata.json
  websites/S/Sorryfield/presence.ts
Labels: activity update

#8993 fix(4chan): add urls
  websites/0-9/4chan/metadata.json
Labels: activity update

#8995 feat(Incels.is): Updated author name (I'm the author), minor tweaks t…
  websites/I/Incels.is/metadata.json
  websites/I/Incels.is/presence.ts
Labels: activity update

#8998 chore(Wbijam): removal of the presence
  websites/W/Wbijam/iframe.ts
  websites/W/Wbijam/metadata.json
  websites/W/Wbijam/presence.ts
Labels: activity deletion

#9002 fix(Spotify Podcasts): show large image cover
  websites/S/Spotify Podcasts/metadata.json
  websites/S/Spotify Podcasts/presence.ts
Labels: activity update

#9006 chore(YouTube): change id to reset setting to default
  websites/Y/YouTube/metadata.json
  websites/Y/YouTube/presence.ts
Labels: activity update

#9008 chore(Incels.is): format metadata
  websites/I/Incels.is/metadata.json
Labels: activity update, repo maintenance, chore

#8994 feat(stremio): many improvements
  websites/S/Stremio/metadata.json
  websites/S/Stremio/presence.ts
Labels: activity update

#8953 feat(StreamEast): add presence
  websites/S/StreamEast/metadata.json
  websites/S/StreamEast/presence.ts
Labels: new activity

#9012 chore(Stremio): update assets
  websites/S/Stremio/metadata.json
  websites/S/Stremio/presence.ts
Labels: activity update, repo maintenance, chore

#9013 chore(StreamEast): update assets
  websites/S/StreamEast/metadata.json
  websites/S/StreamEast/presence.ts
Labels: activity update, repo maintenance, chore

#9019 chore(workflows): update stale issue handling
  .github/workflows/stale.yml
Labels: repo maintenance

#9015 feat(Yandex Music): rewrite presence
  websites/Y/Yandex Music/metadata.json
  websites/Y/Yandex Music/presence.ts
Labels: activity update

#8997 feat(Nitro Type): update presence
  websites/N/Nitro Type/metadata.json
  websites/N/Nitro Type/presence.ts
Labels: activity update

#9016 feat(Studio.Design): add presence
  websites/S/Studio.Design/metadata.json
  websites/S/Studio.Design/presence.ts
Labels: activity creation

#9025 fix(CHZZK): stream info not show
  websites/C/CHZZK/metadata.json
  websites/C/CHZZK/presence.ts
Labels: activity update

#9035 chore(issue_template): change github issue template (presence to activity)
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/service_request.yml
Labels: repo maintenance

#9039 chore(Studio.Design): update assets
  websites/S/Studio.Design/metadata.json
  websites/S/Studio.Design/presence.ts
Labels: activity update, repo maintenance, chore

#9003 feat(Royal Road): add presence
  websites/R/Royal Road/metadata.json
  websites/R/Royal Road/presence.ts
Labels: activity creation
