Repository PreMiD/Activities, pull requests merged in 2025-04, with the labels that each got.

#9391 feat(1Shows): add activity
  websites/0-9/1Shows/metadata.json
  websites/0-9/1Shows/presence.ts
Labels: activity creation

#9400 feat(RTBF Auvio): add activity
  websites/R/RTBF Auvio/RTBF Auvio.json
  websites/R/RTBF Auvio/metadata.json
  websites/R/RTBF Auvio/presence.ts
  websites/R/RTBF Auvio/util.ts
Labels: activity creation

#9235 feat(YNOProject): Draw a pixel of random color to resized image
  websites/Y/YNOProject/metadata.json
  websites/Y/YNOProject/presence.ts
Labels: activity update

#9383 feat(AnimeVsub): add activity
  websites/A/AnimeVsub/metadata.json
  websites/A/AnimeVsub/presence.ts
Labels: activity creation

#9415 feat(Facebook): add more settings & more video types
  websites/F/Facebook/Facebook.json
  websites/F/Facebook/metadata.json
  websites/F/Facebook/presence.ts
Labels: activity update

#9430 feat: add multilanguage to some popular Activities
  websites/G/Google Drive/Google Drive.json
  websites/G/Google Drive/metadata.json
  websites/G/Google Drive/presence.ts
  websites/G/Google Maps/Google Maps.json
  websites/G/Google Maps/metadata.json
  websites/G/Google Maps/presence.ts
  websites/G/Google Messages/Google Messages.json
  websites/G/Google Messages/metadata.json
  websites/G/Google Messages/presence.ts
  websites/G/Google Photos/Google Photos.json
  websites/G/Google Photos/metadata.json
  websites/G/Google Photos/presence.ts
  websites/O/Outlook/Outlook.json
  websites/O/Outlook/metadata.json
  websites/O/Outlook/presence.ts
  websites/X/Xbox/Xbox.json
  websites/X/Xbox/metadata.json
  websites/X/Xbox/presence.ts
Labels: activity update, multiple activities

#9442 feat(Chompu): fix and update activity
  websites/C/Chompu/metadata.json
  websites/C/Chompu/presence.ts
Labels: activity update

#9445 fix(IDLIX): fix strings causing presence to not work
  websites/I/IDLIX/metadata.json
  websites/I/IDLIX/presence.ts
Labels: activity update

#9398 feat(OpenGuessr): add activity
  websites/O/OpenGuessr/metadata.json
  websites/O/OpenGuessr/presence.ts
Labels: activity creation

#9456 fix(UpBeat): Fixed a few minor bugs noticed on the presence + Updated Banner to look sexier
  websites/U/UpBeatRadio/metadata.json
  websites/U/UpBeatRadio/presence.ts
Labels: activity update

#9453 feat(Dreamhack): add activity
  websites/D/Dreamhack/metadata.json
  websites/D/Dreamhack/presence.ts
Labels: activity creation

#9459 feat(MangaLivre): add presence
  websites/M/MangaLivre/metadata.json
  websites/M/MangaLivre/presence.ts
Labels: activity creation

#9465 feat(Império Network): add activity
  websites/I/Império Network/metadata.json
  websites/I/Império Network/presence.ts
Labels: activity creation

#9458 feat(Animevietsub): add feauture
  websites/A/Animevietsub/metadata.json
  websites/A/Animevietsub/presence.ts
Labels: activity update

#9475 fix(Sezonluk Dizi): update domain
  websites/S/Sezonluk Dizi/metadata.json
Labels: activity update

#9474 fix(Freek): update domain
  websites/F/Freek/metadata.json
Labels: activity update

#9478 feat(General): add more general strings & add some descriptions
  websites/general.json
Labels: repo maintenance

#9467 feat(Streaming+): add presence
  websites/S/Streaming+/metadata.json
  websites/S/Streaming+/presence.ts
Labels: activity creation

#9469 feat(Estácio): add activity
  websites/E/Estácio/iframe.ts
  websites/E/Estácio/metadata.json
  websites/E/Estácio/presence.ts
  websites/E/Estácio/utils/index.ts
Labels: activity creation

#9481 feat(Wikipedia): recode activity
  websites/W/Wikipedia/metadata.json
  websites/W/Wikipedia/presence.ts
  websites/W/Wikipedia/wikipedia.json
Labels: activity update

#9480 fix(1Anime): Update domain and activity
  websites/0-9/1Anime/metadata.json
  websites/0-9/1Anime/presence.ts
  websites/0-9/1Anime/utils.ts
Labels: activity update

#9490 fix: editor now shows language & file currently being edited
  websites/C/Crowdin/metadata.json
  websites/C/Crowdin/presence.ts
Labels: activity update

#9504 chore: add country to bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: repo maintenance

#9484 feat(Udio): add activity
  websites/U/Udio/metadata.json
  websites/U/Udio/presence.ts
Labels: activity creation

#9496 fix(Kitsu): update domain
  websites/K/Kitsu/metadata.json
Labels: activity update

#9507 feat(ChatGPT): improve privacy button && add library tab
  websites/C/ChatGPT/ChatGPT.json
  websites/C/ChatGPT/metadata.json
  websites/C/ChatGPT/presence.ts
  websites/C/ChatGPT/util/PrivacyUI.ts
Labels: activity update

#9509 feat(ogladajanime): add SPA support and code optimizations
  websites/O/ogladajanime/metadata.json
  websites/O/ogladajanime/presence.ts
Labels: activity update

#9502 feat(Club Penguin Journey): New Rooms and Images for Rooms
  websites/C/Club Penguin Journey/assets.ts
  websites/C/Club Penguin Journey/metadata.json
  websites/C/Club Penguin Journey/presence.ts
Labels: activity update

#9500 feat(Anizium): remove thumbnail element
  websites/A/Anizium/metadata.json
  websites/A/Anizium/presence.ts
Labels: activity update

#9510 fix(DeepL): rework Activity
  websites/D/DeepL/DeepL.json
  websites/D/DeepL/metadata.json
  websites/D/DeepL/presence.ts
Labels: activity update

#9495 fix: change regex && repairing the Google Calendar Activity
  websites/G/Google Calendar/Google Calendar.json
  websites/G/Google Calendar/metadata.json
  websites/G/Google Calendar/presence.ts
  websites/G/Google Docs/metadata.json
  websites/G/Google Docs/presence.ts
  websites/G/Google Drive/metadata.json
  websites/G/Google Drive/presence.ts
  websites/G/Google Maps/Google Maps.json
  websites/G/Google Maps/metadata.json
  websites/G/Google Maps/presence.ts
  websites/G/Google Photos/metadata.json
  websites/G/Google Photos/presence.ts
Labels: activity update, multiple activities

#9517 feat(neal.fun): add stimulation clicker
  websites/N/neal.fun/metadata.json
  websites/N/neal.fun/presence.ts
Labels: activity update

#9522 feat(Anizium): Re-code and update presence
  websites/A/Anizium/metadata.json
  websites/A/Anizium/presence.ts
Labels: activity update

#9518 feat(Medal): add activity
  websites/M/Medal/metadata.json
  websites/M/Medal/presence.ts
Labels: activity creation

#9524 fix(TruckersFM): new description & better translation
  websites/T/TruckersFM/metadata.json
Labels: activity update
