Repository PreMiD/Activities, pull requests merged in 2025-06, with the labels that each got.

#9652 chore(Hikari.gg): remove Activity
  websites/H/Hikari/metadata.json
  websites/H/Hikari/presence.ts
Labels: activity deletion

#9649 feat:(TMBW): corrected the author's user id
  websites/T/TMBW/metadata.json
Labels: activity update

#9656 feat(YTPLR): Add Mirror
  websites/Y/YTPLR/metadata.json
  websites/Y/YTPLR/presence.ts
Labels: activity update

#9634 chore(invidious): update urls
  websites/I/Invidious/metadata.json
Labels: activity update

#9660 feat(Bíblia On-line): add activity
  websites/B/Bíblia On-line/metadata.json
  websites/B/Bíblia On-line/presence.ts
Labels: activity creation

#9669 feat(Navidrome): add covers, listening and artist as title
  websites/N/Navidrome/metadata.json
  websites/N/Navidrome/presence.ts
Labels: activity update

#9637 feat(Asmrone): add activity
  websites/A/Asmrone/metadata.json
  websites/A/Asmrone/presence.ts
Labels: activity creation

#9664 feat(iQIYIs): add activity
  websites/I/iQIYIs/metadata.json
  websites/I/iQIYIs/presence.ts
Labels: activity creation

#9648 feat(iFixit): add activity
  websites/I/iFixit/functions/fetchGuideMetadata.ts
  websites/I/iFixit/functions/getClosestStep.ts
  websites/I/iFixit/iFixit.json
  websites/I/iFixit/metadata.json
  websites/I/iFixit/package-lock.json
  websites/I/iFixit/package.json
  websites/I/iFixit/presence.ts
  websites/I/iFixit/types.ts
Labels: activity creation

#9662 feat(Sunniesnow): add activity
  websites/S/Sunniesnow/metadata.json
  websites/S/Sunniesnow/presence.ts
Labels: activity creation

#9674 feat(AnimeKai): update supported urls
  websites/A/AnimeKai/metadata.json
  websites/A/AnimeKai/presence.ts
Labels: activity update

#9659 feat(AnimeDekho): update activity
  websites/A/AnimeDekho/iframe.ts
  websites/A/AnimeDekho/metadata.json
  websites/A/AnimeDekho/presence.ts
Labels: activity update

#9672 feat(GeoGuessr): update activity
  websites/G/GeoGuessr/GeoGuessr.json
  websites/G/GeoGuessr/assets.ts
  websites/G/GeoGuessr/metadata.json
  websites/G/GeoGuessr/presence.ts
Labels: activity update

#9681 feat(AnimeKai): Update Presence functions
  websites/A/AnimeKai/metadata.json
  websites/A/AnimeKai/presence.ts
Labels: activity update

#9653 feat(Kuroiru): add activity
  websites/K/Kuroiru/metadata.json
  websites/K/Kuroiru/presence.ts
Labels: activity creation

#9679 feat(MangaLib): rewrite activity
  websites/A/AnimeLib/lib.ts
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
  websites/M/Mangalib/api/cdnlibs.ts
  websites/M/Mangalib/api/lib.ts
  websites/M/Mangalib/api/models/anime.ts
  websites/M/Mangalib/api/models/character.ts
  websites/M/Mangalib/api/models/collections.ts
  websites/M/Mangalib/api/models/common.ts
  websites/M/Mangalib/api/models/manga.ts
  websites/M/Mangalib/api/models/people.ts
  websites/M/Mangalib/api/models/publisher.ts
  websites/M/Mangalib/api/models/ranobe.ts
  websites/M/Mangalib/api/models/reviews.ts
  websites/M/Mangalib/api/models/teams.ts
  websites/M/Mangalib/api/models/user.ts
  websites/M/Mangalib/api/utils.ts
  websites/M/Mangalib/iframe.ts
  websites/M/Mangalib/metadata.json
  websites/M/Mangalib/presence.ts
Labels: activity update, activity deletion

#9705 chore(Ranobelib): remove activity
  websites/R/Ranobelib/metadata.json
  websites/R/Ranobelib/presence.ts
Labels: activity deletion

#9703 feat(RetroCrush): add activity
  websites/R/RetroCrush/metadata.json
  websites/R/RetroCrush/presence.ts
Labels: activity creation

#9715 feat(GOG): new mods page
  websites/G/GOG/GOG.json
  websites/G/GOG/metadata.json
  websites/G/GOG/presence.ts
Labels: activity update

#9699 feat(Hashnode): add activity
  websites/H/Hashnode/metadata.json
  websites/H/Hashnode/presence.ts
Labels: activity creation

#9718 feat(AnimEly): add activity
  websites/A/AnimEly/iframe.ts
  websites/A/AnimEly/metadata.json
  websites/A/AnimEly/presence.ts
Labels: activity creation

#9712 feat(DarkWave): add activity
  websites/D/Dark Wave/metadata.json
  websites/D/Dark Wave/presence.ts
Labels: activity creation

#9730 chore: remove activities for dmca
  websites/A/AnimeUnity/iframe.ts
  websites/A/AnimeUnity/metadata.json
  websites/A/AnimeUnity/presence.ts
  websites/K/KimCartoon/iframe.ts
  websites/K/KimCartoon/metadata.json
  websites/K/KimCartoon/presence.ts
  websites/M/MangaFire/metadata.json
  websites/M/MangaFire/presence.ts
Labels: activity deletion, multiple activities, chore, dmca

#9725 feat(Enka.Network): add activity
  websites/E/Enka.Network/metadata.json
  websites/E/Enka.Network/presence.ts
Labels: activity creation
