Repository PreMiD/Activities, pull requests merged in 2025-05, with the labels that each got.

#9374 feat(Khan Academy): fix and update presence
  websites/K/Khan Academy/metadata.json
  websites/K/Khan Academy/presence.ts
Labels: activity update

#9525 feat(Microsoft Learn): add new presence
  websites/M/Microsoft Learn/metadata.json
  websites/M/Microsoft Learn/presence.ts
Labels: activity creation

#9487 fix(Simulator Radio): remove listener count
  websites/S/Simulator Radio/metadata.json
  websites/S/Simulator Radio/presence.ts
Labels: inactive, activity update

#9491 refactor(Twitch): udpate French description
  websites/T/Twitch/metadata.json
Labels: activity update

#9534 feat(Dreamhack): update activity
  websites/D/Dreamhack/metadata.json
  websites/D/Dreamhack/presence.ts
Labels: activity update

#9543 fix(SoundCloud): replace asset key with link
  websites/S/SoundCloud/metadata.json
  websites/S/SoundCloud/presence.ts
Labels: activity update

#9553 chore(Reaper Scans): remove activity
  websites/R/Reaper Scans/metadata.json
  websites/R/Reaper Scans/presence.ts
Labels: activity deletion

#9552 fix(TradingView): update logo & thumbnail
  websites/T/TradingView/metadata.json
  websites/T/TradingView/presence.ts
Labels: activity update

#9558 refactor(Watch-Anime): update contributors
  websites/W/Watch-Anime/metadata.json
Labels: activity update

#9536 feat(sekolahmu): add new presence
  websites/S/sekolahmu/metadata.json
  websites/S/sekolahmu/presence.ts
Labels: activity creation

#9549 feat(Hexa Watch): add activity
  websites/H/Hexa Watch/metadata.json
  websites/H/Hexa Watch/presence.ts
Labels: activity creation

#9564 feat(cli): add fallback username to discord username api
  cli/package.json
  cli/src/util/getDiscordUser.ts
Labels: repo maintenance

#9572 feat(Sketchful.io): add activity
  websites/S/Sketchful.io/metadata.json
  websites/S/Sketchful.io/presence.ts
Labels: activity creation

#9566 feat(Playlist Randomizer): add activity
  websites/P/Playlist Randomizer/iframe.ts
  websites/P/Playlist Randomizer/metadata.json
  websites/P/Playlist Randomizer/presence.ts
Labels: activity creation

#9546 feat(Blooket): add Blooket activity
  websites/B/Blooket/metadata.json
  websites/B/Blooket/presence.ts
Labels: activity creation

#9565 feat(Wuthering Waves): add activity
  websites/W/Wuthering Waves/Wuthering Waves.json
  websites/W/Wuthering Waves/metadata.json
  websites/W/Wuthering Waves/presence.ts
Labels: activity creation

#9569 feat(Hikari): add activity
  websites/H/Hikari/metadata.json
  websites/H/Hikari/presence.ts
Labels: activity creation

#9574 feat(5etools): add 2014 subdomain
  websites/0-9/5etools/metadata.json
  websites/0-9/5etools/presence.ts
Labels: activity update

#9573 feat(YouTube): add chapter support
  websites/Y/YouTube/metadata.json
  websites/Y/YouTube/presence.ts
  websites/Y/YouTube/util/index.ts
Labels: activity update

#9580 feat(Twitch): add streamer as title setting
  websites/T/Twitch/metadata.json
  websites/T/Twitch/presence.ts
Labels: activity update

#9577 feat(Prydwen Institute): update for new website
  websites/P/Prydwen Institute/games/afk-journey.ts
  websites/P/Prydwen Institute/games/arknights-endfield.ts
  websites/P/Prydwen Institute/games/ash-echoes.ts
  websites/P/Prydwen Institute/games/counter-side.ts
  websites/P/Prydwen Institute/games/etheria-restart.ts
  websites/P/Prydwen Institute/games/eversoul.ts
  websites/P/Prydwen Institute/games/gfl-exilium.ts
  websites/P/Prydwen Institute/games/index.ts
  websites/P/Prydwen Institute/games/limbus-company.ts
  websites/P/Prydwen Institute/games/nikke.ts
  websites/P/Prydwen Institute/games/re1999.ts
  websites/P/Prydwen Institute/games/solo-leveling.ts
  websites/P/Prydwen Institute/games/star-rail.ts
  websites/P/Prydwen Institute/games/wuthering-waves.ts
  websites/P/Prydwen Institute/games/zenless.ts
  websites/P/Prydwen Institute/lists.ts
  websites/P/Prydwen Institute/metadata.json
  websites/P/Prydwen Institute/presence.ts
  websites/P/Prydwen Institute/util.ts
Labels: activity update

#9571 feat(AniKenjiMovie): Add activity
  websites/A/AniKenji Movie/iframe.ts
  websites/A/AniKenji Movie/metadata.json
  websites/A/AniKenji Movie/presence.ts
Labels: activity creation

#9582 feat(RoyaleAPI): add activity
  websites/R/RoyaleAPI/RoyaleAPI.json
  websites/R/RoyaleAPI/iframe.ts
  websites/R/RoyaleAPI/metadata.json
  websites/R/RoyaleAPI/presence.ts
  websites/R/RoyaleAPI/util.ts
Labels: activity creation

#9579 refactor: add general strings type hints to Presence#getStrings
  @types/premid/index.d.ts
Labels: repo maintenance

#9593 feat(AniKenji Movie): Update for new Theme
  websites/A/AniKenji Movie/metadata.json
  websites/A/AniKenji Movie/presence.ts
Labels: activity update

#9600 fix(Novastream): fix rating display & add /index.html support
  websites/N/NovaStream/presence.ts
Labels: activity update

#9601 feat(Novastream): add support for settings page
  websites/N/NovaStream/metadata.json
  websites/N/NovaStream/presence.ts
Labels: activity update

#9602 feat(EverythingMoe): add activity
  websites/E/EverythingMoe/metadata.json
  websites/E/EverythingMoe/presence.ts
Labels: activity creation

#9608 feat(YouTube Music): add 'Show Artist as Title' setting
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9607 feat(Beatport): add activity
  websites/B/Beatport/metadata.json
  websites/B/Beatport/presence.ts
Labels: activity creation

#9610 fix(Hero Forge): update item selectors
  websites/H/Hero Forge/metadata.json
  websites/H/Hero Forge/presence.ts
Labels: activity update

#9609 refactor: fix activity type assignment
  websites/0-9/1Anime/metadata.json
  websites/0-9/1Anime/presence.ts
  websites/A/AnimeKai/metadata.json
  websites/A/AnimeKai/presence.ts
  websites/A/AnimeciX/metadata.json
  websites/A/AnimeciX/presence.ts
  websites/A/AnizmTV/presence.ts
  websites/F/Facebook/metadata.json
  websites/F/Facebook/presence.ts
  websites/I/iQIYI/metadata.json
  websites/I/iQIYI/presence.ts
  websites/M/Medal/metadata.json
  websites/M/Medal/presence.ts
  websites/N/niconico/metadata.json
  websites/N/niconico/presence.ts
  websites/O/OnlyHit/metadata.json
  websites/O/OnlyHit/presence.ts
  websites/R/RoyaleAPI/metadata.json
  websites/R/RoyaleAPI/presence.ts
  websites/V/VLC/metadata.json
  websites/V/VLC/presence.ts
  websites/V/VocaDB/metadata.json
  websites/V/VocaDB/presence.ts
  websites/W/Wave FM/metadata.json
  websites/W/Wave FM/presence.ts
Labels: activity update, multiple activities, repo maintenance

#9605 feat(NeedCoolerShoes): add activity
  websites/N/NeedCoolerShoes/metadata.json
  websites/N/NeedCoolerShoes/presence.ts
Labels: activity creation

#9589 feat(Editor for Blather 'Round): add activity
  websites/E/Editor for Blather 'Round/metadata.json
  websites/E/Editor for Blather 'Round/presence.ts
Labels: activity creation

#9588 feat(Deck Shop): add activity
  websites/D/Deck Shop/Deck Shop.json
  websites/D/Deck Shop/metadata.json
  websites/D/Deck Shop/presence.ts
Labels: activity creation

#9612 feat(Emurse): add activity
  websites/E/Emurse/metadata.json
  websites/E/Emurse/presence.ts
Labels: activity creation

#9611 feat(Wink): add activity
  websites/W/Wink/iframe.ts
  websites/W/Wink/metadata.json
  websites/W/Wink/presence.ts
  websites/W/Wink/utils/utils.ts
Labels: activity creation

#9615 fix(AnimeGO): add regexp for mirrors
  websites/A/AnimeGO/metadata.json
Labels: activity update

#9616 chore(NeedCoolerShoes): update thumbnail
  websites/N/NeedCoolerShoes/metadata.json
Labels: activity update

#9614 fix(Yandex Music): update definition player
  websites/Y/Yandex Music/metadata.json
  websites/Y/Yandex Music/presence.ts
Labels: activity update

#9595 feat(Tide Radio): add activity
  websites/T/Tide Radio/metadata.json
  websites/T/Tide Radio/presence.ts
Labels: activity creation

#9619 feat(RankOne): add activity
  websites/R/RankOne/RankOne.json
  websites/R/RankOne/metadata.json
  websites/R/RankOne/presence.ts
Labels: activity creation

#9621 feat(Best Buy): add activity
  websites/B/Best Buy/metadata.json
  websites/B/Best Buy/presence.ts
Labels: activity creation

#9625 chore(movie-web): Update urls and meta
  websites/M/movie-web/metadata.json
  websites/M/movie-web/presence.ts
Labels: activity update

#9620 feat(NPR): add activity
  websites/N/NPR/metadata.json
  websites/N/NPR/presence.ts
Labels: activity creation

#9631 chore(TugaStrikes): remove activity
  websites/T/TugaStrikes/metadata.json
  websites/T/TugaStrikes/presence.ts
Labels: activity deletion, repo maintenance

#9630 feat(The Verge): add activity
  websites/T/The Verge/metadata.json
  websites/T/The Verge/presence.ts
Labels: activity creation

#9623 feat(This Might Be A Wiki): add activity
  websites/T/TMBW/metadata.json
  websites/T/TMBW/presence.ts
Labels: activity creation

#9647 chore(Skype): remove activity
  websites/S/Skype/metadata.json
  websites/S/Skype/presence.ts
Labels: activity deletion

#9640 feat(OtakuPT): add activity
  websites/O/OtakuPT/metadata.json
  websites/O/OtakuPT/presence.ts
Labels: activity creation

#9645 feat(Anime Dekho): add activity
  websites/A/AnimeDekho/metadata.json
  websites/A/AnimeDekho/presence.ts
Labels: activity creation
