Repository PreMiD/Activities, pull requests merged in 2025-08, with the labels that each got.

#9831 feat(Anroll): add activity
  websites/A/Anroll/iframe.ts
  websites/A/Anroll/metadata.json
  websites/A/Anroll/presence.ts
Labels: activity creation

#9829 feat(Panais): add activity
  websites/P/Panais/metadata.json
  websites/P/Panais/presence.ts
Labels: activity creation

#9817 feat(MyFigureCollection): add activity
  websites/M/MyFigureCollection.net/MyFigureCollection.net.json
  websites/M/MyFigureCollection.net/metadata.json
  websites/M/MyFigureCollection.net/pages/BlogPostPage.ts
  websites/M/MyFigureCollection.net/pages/ClassifiedPage.ts
  websites/M/MyFigureCollection.net/pages/ClubPage.ts
  websites/M/MyFigureCollection.net/pages/EntryPage.ts
  websites/M/MyFigureCollection.net/pages/ItemPage.ts
  websites/M/MyFigureCollection.net/pages/ListPage.ts
  websites/M/MyFigureCollection.net/pages/PicturePage.ts
  websites/M/MyFigureCollection.net/pages/ShopPage.ts
  websites/M/MyFigureCollection.net/pages/TagPage.ts
  websites/M/MyFigureCollection.net/pages/ThreadPage.ts
  websites/M/MyFigureCollection.net/pages/UserPage.ts
  websites/M/MyFigureCollection.net/pages/base.ts
  websites/M/MyFigureCollection.net/pages/index.ts
  websites/M/MyFigureCollection.net/presence.ts
  websites/M/MyFigureCollection.net/util.ts
Labels: activity creation

#9836 fix(Vinted): Add all domains
  websites/V/Vinted/metadata.json
Labels: activity update

#9832 feat(Flemmix): add presence
  websites/F/Flemmix/iframe.ts
  websites/F/Flemmix/metadata.json
  websites/F/Flemmix/presence.ts
Labels: activity creation

#9847 feat(Watch-Anime): update activity
  websites/W/Watch-Anime/metadata.json
  websites/W/Watch-Anime/presence.ts
Labels: activity update

#9842 feat(Panais): add progress bar
  websites/P/Panais/metadata.json
  websites/P/Panais/presence.ts
Labels: activity update

#9848 fix(Physics Wallah): Updated the application id
  websites/P/Physics Wallah/metadata.json
  websites/P/Physics Wallah/presence.ts
Labels: activity update

#9845 feat(Wplace): add activity
  websites/W/Wplace/metadata.json
  websites/W/Wplace/presence.ts
Labels: activity creation

#9463 feat(docs): add VitePress documentation
  .github/workflows/deploy-docs.yml
  .github/workflows/vhs.yaml
  @types/premid/index.d.ts
  docs/.gitignore
  docs/.vitepress/config.ts
  docs/README.md
  docs/activity-forwarding.md
  docs/images/activity-forwarding-setting.png
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/public/tapes/create-activity.gif
  docs/public/tapes/developing-activity.gif
  docs/tapes/create-activity.tape
  docs/tapes/developing-activity.tape
  docs/tsconfig.json
  docs/v1/api/iframe.md
  docs/v1/api/index.md
  docs/v1/api/metadata-json.md
  docs/v1/api/presence-class.md
  docs/v1/api/presence-data.md
  docs/v1/api/slideshow.md
  docs/v1/api/utility-functions.md
  docs/v1/examples/iframes.md
  docs/v1/examples/index.md
  docs/v1/examples/media.md
  docs/v1/examples/settings.md
  docs/v1/examples/slideshow.md
  docs/v1/guide/best-practices.md
  docs/v1/guide/dependencies.md
  docs/v1/guide/developer-tools.md
  docs/v1/guide/first-activity.md
  docs/v1/guide/guidelines.md
  docs/v1/guide/iframes.md
  docs/v1/guide/index.md
  docs/v1/guide/installation.md
  docs/v1/guide/loading-activities.md
  docs/v1/guide/localization.md
  docs/v1/guide/metadata.md
  docs/v1/guide/presence-class.md
  docs/v1/guide/settings.md
  docs/v1/guide/slideshows.md
  docs/v1/guide/structure.md
  docs/v1/index.md
  docs/v2/todo.md
Labels: repo maintenance

#9862 feat(Physics Wallah): Added a new feature where it shows up as viewing notes
  websites/P/Physics Wallah/metadata.json
  websites/P/Physics Wallah/presence.ts
Labels: activity update

#9870 feat(dcinside): add activity
  websites/D/dcinside/metadata.json
  websites/D/dcinside/presence.ts
Labels: activity creation

#9875 fix(AniKenji Movie): fix not display title and add support new domain
  websites/A/AniKenji Movie/metadata.json
  websites/A/AniKenji Movie/presence.ts
Labels: activity update

#9873 feat(WitAnime): add activity
  websites/W/WitAnime/iframe.ts
  websites/W/WitAnime/metadata.json
  websites/W/WitAnime/presence.ts
Labels: activity creation

#9882 feat(Deezer): extract main artist name for presence data
  websites/D/Deezer/metadata.json
  websites/D/Deezer/presence.ts
Labels: activity update

#9884 fix(Wplace): add privacy settings
  websites/W/Wplace/metadata.json
  websites/W/Wplace/presence.ts
Labels: activity update

#9885 feat(NixOS): add activity
  websites/N/NixOS/metadata.json
  websites/N/NixOS/presence.ts
Labels: activity creation

#9886 feat(Rooster Teeth): add activity
  websites/R/Rooster Teeth/iframe.ts
  websites/R/Rooster Teeth/metadata.json
  websites/R/Rooster Teeth/presence.ts
Labels: activity creation

#9891 feat(Anroll): complete overhaul and new features
  websites/A/AnROLL/metadata.json
  websites/A/AnROLL/presence.ts
Labels: activity update

#9867 feat(OnShape): add presence activity
  websites/O/OnShape/metadata.json
  websites/O/OnShape/presence.ts
Labels: activity creation

#9908 fix(Fandom): Fix activity does not show and refactor some logics
  websites/F/Fandom/metadata.json
  websites/F/Fandom/presence.ts
Labels: activity update

#9912 feat(FFXIV Lodestone): add activity
  websites/F/FFXIV Lodestone/metadata.json
  websites/F/FFXIV Lodestone/presence.ts
Labels: activity creation

#9906 refactor(Anizium): Rewrite presence for detailed page support
  websites/A/Anizium/handlers/route.ts
  websites/A/Anizium/managers/poster.ts
  websites/A/Anizium/managers/settings.ts
  websites/A/Anizium/metadata.json
  websites/A/Anizium/presence.ts
  websites/A/Anizium/types.ts
  websites/A/Anizium/utils.ts
Labels: activity update

#9897 feat(websites): added tlx.toki.id presence
  websites/T/TLX Toki/metadata.json
  websites/T/TLX Toki/presence.ts
Labels: activity creation

#9936 feat(Sky Sports): add presence
  websites/S/Sky Sports/metadata.json
  websites/S/Sky Sports/presence.ts
Labels: activity creation

#9923 chore(deps): update dependencies
  .github/workflows/assets-updater.yml
  .github/workflows/crowdin.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/eslint.yml
  .github/workflows/pmd.yml
  .github/workflows/release.yml
  .github/workflows/vhs.yaml
  cli/package-lock.json
  cli/package.json
  docs/package-lock.json
  docs/package.json
  package-lock.json
  package.json
  websites/G/Grok/metadata.json
  websites/G/Grok/package-lock.json
  websites/G/Grok/package.json
  websites/I/iFixit/metadata.json
  websites/I/iFixit/package-lock.json
  websites/I/iFixit/package.json
  websites/N/Netflix/metadata.json
  websites/N/Netflix/package-lock.json
  websites/N/Netflix/package.json
  websites/U/U-NEXT/metadata.json
  websites/U/U-NEXT/package-lock.json
  websites/U/U-NEXT/package.json
Labels: dependencies, repo maintenance, chore

#9932 chore(Bluesky): update logo
  websites/B/Bluesky/metadata.json
  websites/B/Bluesky/presence.ts
Labels: activity update

#9776 fix(AniWorld): fix translation + add cover cache
  websites/A/AniWorld/metadata.json
  websites/A/AniWorld/presence.ts
Labels: activity update

#9907 fix(monkeytype): resolve undefined stats, correct test time, add loading state
  websites/M/Monkeytype/metadata.json
  websites/M/Monkeytype/presence.ts
Labels: activity update
