Repository PreMiD/Activities, pull requests merged in 2025-03, with the labels that each got.

#9351 feat(cli): display help message when no command is matched
  cli/src/index.ts
Labels: repo maintenance

#9280 feat(Teckie): add Teckie support
  websites/T/Teckie/metadata.json
  websites/T/Teckie/presence.ts
Labels: activity creation

#9291 feat(General.json): add more strings and make strings consistent across activities
  websites/0-9/7tv/presence.ts
  websites/A/Apple/presence.ts
  websites/A/animepahe/presence.ts
  websites/D/Discord/metadata.json
  websites/D/Discord/presence.ts
  websites/E/Eurogamer/metadata.json
  websites/E/Eurogamer/presence.ts
  websites/G/Google Docs/metadata.json
  websites/H/Habr/presence.ts
  websites/H/Hoyolab/metadata.json
  websites/H/Hoyolab/presence.ts
  websites/K/KickAssAnime/metadata.json
  websites/K/KickAssAnime/presence.ts
  websites/M/MangaKatana/presence.ts
  websites/N/NameMC/presence.ts
  websites/O/OK/presence.ts
  websites/O/osu ppy/presence.ts
  websites/P/Panda Novel/metadata.json
  websites/P/Panda Novel/presence.ts
  websites/P/Pokéflix/metadata.json
  websites/P/Pokéflix/presence.ts
  websites/P/PreMiD/metadata.json
  websites/P/PreMiD/presence.ts
  websites/S/Spotify Podcasts/metadata.json
  websites/S/Spotify Podcasts/presence.ts
  websites/T/Twitch/presence.ts
  websites/V/VRV/metadata.json
  websites/V/VRV/presence.ts
  websites/V/VRoid/metadata.json
  websites/V/VRoid/presence.ts
  websites/X/X.com/metadata.json
  websites/X/X.com/presence.ts
  websites/Z/Zerion/presence.ts
  websites/general.json
Labels: activity update, multiple activities, repo maintenance

#9358 fix(CLI): make options consistent
  cli/src/index.ts
Labels: repo maintenance

#9346 feat(Raycast): add Raycast presence
  websites/R/Raycast/metadata.json
  websites/R/Raycast/presence.ts
Labels: activity creation

#9349 fix(DevianArt): don't show undefined in gallery
  websites/D/DeviantArt/metadata.json
  websites/D/DeviantArt/presence.ts
Labels: activity update

#9356 refactor(Deezer): change activity type from game to listening
  websites/D/Deezer/metadata.json
  websites/D/Deezer/presence.ts
Labels: activity update

#9362 feat(Suno): add activity
  websites/S/Suno/metadata.json
  websites/S/Suno/presence.ts
Labels: activity creation

#9365 feat(Inlx): add Inlx presence
  websites/I/Inlx/metadata.json
  websites/I/Inlx/presence.ts
Labels: activity creation

#9352 feat(The StoryGraph): add The StoryGraph activity
  websites/T/The StoryGraph/The StoryGraph.json
  websites/T/The StoryGraph/metadata.json
  websites/T/The StoryGraph/presence.ts
Labels: activity creation

#9367 feat(Quizypedia): add Quizypedia presence
  websites/Q/Quizypedia/metadata.json
  websites/Q/Quizypedia/presence.ts
Labels: activity creation

#9375 chore(deps): update dependencies
  .github/renovate.json
  cli/package-lock.json
  cli/package.json
  package-lock.json
  package.json
  websites/N/Netflix/metadata.json
  websites/N/Netflix/package-lock.json
  websites/N/Netflix/package.json
  websites/U/U-NEXT/metadata.json
  websites/U/U-NEXT/package-lock.json
  websites/U/U-NEXT/package.json
Labels: dependencies

#9380 chore: delete Google Domains Activity
  websites/G/Google Domains/metadata.json
  websites/G/Google Domains/presence.ts
Labels: activity deletion

#9386 chore(release): replace mongodb with management endpoint
  .github/workflows/release.yml
  cli/package.json
  cli/src/commands/release.ts
  cli/src/util/log.ts
Labels: repo maintenance

#9387 feat(Backloggd): also support www.domain
  websites/B/Backloggd/metadata.json
Labels: activity update

#9381 feat(Chorki): add Chorki presence
  websites/C/Chorki/metadata.json
  websites/C/Chorki/presence.ts
Labels: activity creation

#9378 chore(bilibili): add chinese altname
  websites/B/bilibili/metadata.json
Labels: activity update

#9372 feat(Pi Fansubs): Movie or TV Show as activity name
  websites/P/Pi Fansubs/metadata.json
  websites/P/Pi Fansubs/presence.ts
Labels: activity update

#9393 fix(IDLIX): simplify regex
  websites/I/IDLIX/metadata.json
  websites/I/IDLIX/presence.ts
Labels: activity update

#9392 fix(Plex): local images not getting uploaded
  websites/P/Plex/metadata.json
  websites/P/Plex/presence.ts
Labels: activity update

#9408 feat(AnimeLib): support for licensed animes
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9406 chore: upgrade inquirer dependency
  cli/package-lock.json
  cli/package.json
  cli/src/commands/bump.ts
  cli/src/commands/new.ts
  cli/src/index.ts
  cli/src/util/getSingleActivity.ts
  cli/src/util/mapActivityToChoice.ts
  package-lock.json
Labels: dependencies, repo maintenance

#9410 Feat(Nexon): add activity
  websites/N/Nexon/metadata.json
  websites/N/Nexon/presence.ts
Labels: activity creation

#9416 feat(Bun): add acitivity
  websites/B/Bun/metadata.json
  websites/B/Bun/presence.ts
Labels: activity creation

#9425 feat(ChatGPT): add some features
  websites/C/ChatGPT/ChatGPT.json
  websites/C/ChatGPT/metadata.json
  websites/C/ChatGPT/presence.ts
Labels: activity update

#9426 chore: update lint command in PR template
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: repo maintenance

#9424 feat(Emby): add app domain
  websites/E/Emby/metadata.json
Labels: activity update

#9419 feat(iQIYI): add watch type and change to destructured variables
  websites/I/iQIYI/metadata.json
  websites/I/iQIYI/presence.ts
Labels: activity update

#9436 feat(notespace): remove activity
  websites/N/notespace/metadata.json
  websites/N/notespace/presence.ts
Labels: activity deletion

#9431 chore(docs): fix typos in contribution guide
  .github/CONTRIBUTING.md
Labels: repo maintenance

#9385 feat(Hulu): add watching to activity
  websites/H/Hulu/Hulu.json
  websites/H/Hulu/metadata.json
  websites/H/Hulu/presence.ts
Labels: activity update

#9399 feat(Chorki): Added missing Playback Bar
  websites/C/Chorki/metadata.json
  websites/C/Chorki/presence.ts
Labels: activity update

#9405 feat(Grok): add activity
  websites/G/Grok/Grok.json
  websites/G/Grok/functions/fetchResponsesMetadata.ts
  websites/G/Grok/metadata.json
  websites/G/Grok/package-lock.json
  websites/G/Grok/package.json
  websites/G/Grok/presence.ts
  websites/G/Grok/types.ts
Labels: activity creation

#9434 feat(x.com): add privacy level support
  websites/X/X.com/metadata.json
  websites/X/X.com/presence.ts
Labels: activity update

#9432 feat(ChatGPT): support shared chat
  websites/C/ChatGPT/ChatGPT.json
  websites/C/ChatGPT/metadata.json
  websites/C/ChatGPT/presence.ts
Labels: activity update

#9411 feat(UpBeat): Recoded a couple bits
  websites/U/UpBeatRadio/metadata.json
  websites/U/UpBeatRadio/presence.ts
Labels: activity update

#9427 feat(Wave FM): add activity
  websites/W/Wave FM/metadata.json
  websites/W/Wave FM/presence.ts
Labels: activity creation

#9428 feat(NicoNico): rewrite activity and add settings
  websites/N/niconico/iframe.ts
  websites/N/niconico/metadata.json
  websites/N/niconico/presence.ts
Labels: activity update

#9429 fix(BeatLeader): update URLs & fix deprecated & fix regex
  websites/B/BeatLeader/metadata.json
  websites/B/BeatLeader/presence.ts
Labels: activity update
