Repository PreMiD/Activities, pull requests merged in 2025-01, with the labels that each got.

#9023 feat(AnimeLib): new presence
  websites/A/AnimeLib/iframe.ts
  websites/A/AnimeLib/lib.ts
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity creation

#9024 fix(StreamingCommunity): update domain
  websites/S/StreamingCommunity/metadata.json
Labels: activity update

#9033 chore: remove spaces from strings and delete: V Live Presence
  websites/G/Google Classroom/metadata.json
  websites/G/Google Classroom/presence.ts
  websites/G/Google Docs/metadata.json
  websites/G/Google Docs/presence.ts
  websites/V/V LIVE/metadata.json
  websites/V/V LIVE/presence.ts
Labels: activity update, activity deletion, multiple activities, repo maintenance

#9054 feat(Zombies World Records): add presence
  websites/Z/Zombies World Records/metadata.json
  websites/Z/Zombies World Records/presence.ts
Labels: activity creation

#9037 feat(HEO Systems): add presence
  websites/H/HEO Systems/metadata.json
  websites/H/HEO Systems/presence.ts
Labels: activity creation

#9040 chore(CHZZK): format metadata
  websites/C/CHZZK/metadata.json
Labels: activity update, repo maintenance, chore

#9044 fix(RTLplay): movie and channel media issues
  websites/R/RTLplay/metadata.json
  websites/R/RTLplay/presence.ts
  websites/R/RTLplay/util.ts
Labels: activity update

#9042 chore(Royal Road): update assets
  websites/R/Royal Road/metadata.json
  websites/R/Royal Road/presence.ts
Labels: activity update, repo maintenance, chore

#9047 feat(GoPlay): use watching type & remove settings
  websites/G/GoPlay/metadata.json
  websites/G/GoPlay/presence.ts
Labels: activity update

#9056 chore(AnimeLib): update assets
  websites/A/AnimeLib/lib.ts
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update, repo maintenance, chore

#9060 chore(Zombies World Records): update assets
  websites/Z/Zombies World Records/metadata.json
  websites/Z/Zombies World Records/presence.ts
Labels: activity update, chore

#9064 chore(vscode): disable Discord integration in settings
  .gitignore
  .vscode/settings.json
Labels: repo maintenance, chore

#9062 chore(RTLPlay): update assets
  websites/R/RTLplay/metadata.json
  websites/R/RTLplay/util.ts
Labels: activity update, chore

#9068 chore(HEO Systems): update assets
  websites/H/HEO Systems/metadata.json
  websites/H/HEO Systems/presence.ts
Labels: activity update, chore

#9053 chore(DMOJ): update discord account
  websites/D/DMOJ/metadata.json
Labels: activity update, chore

#9072 feat(AnimeLib): add privacy mode for 'reviews' case
  websites/A/AnimeLib/lib.ts
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9049 fix(Netflix): pause and showsmallimages issues
  websites/N/Netflix/metadata.json
  websites/N/Netflix/presence.ts
Labels: activity update

#8992 feat(Dek-d): add presence
  websites/D/Dek-d/metadata.json
  websites/D/Dek-d/presence.ts
Labels: activity creation

#9071 chore(Zalando): rewrite activity
  websites/Z/Zalando/metadata.json
  websites/Z/Zalando/presence.ts
Labels: activity update

#9073 chore(Dek-d): update assets
  websites/D/Dek-d/metadata.json
  websites/D/Dek-d/presence.ts
Labels: activity update, chore

#9077 chore(HBO Max): remove activity
  websites/H/HBO Max/metadata.json
  websites/H/HBO Max/presence.ts
Labels: activity deletion

#9075 feat(AnimeLib): add support for buttons
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9014 feat(Freek): add presence
  websites/F/Freek/iframe.ts
  websites/F/Freek/metadata.json
  websites/F/Freek/presence.ts
Labels: activity creation

#9055 feat(Sushi Scan): add presence
  websites/S/Sushi Scan/metadata.json
  websites/S/Sushi Scan/presence.ts
Labels: activity creation

#9081 feat(SOOP): add activity
  websites/S/SOOP/metadata.json
  websites/S/SOOP/presence.ts
Labels: activity creation

#9085 feat(WeTV): add cover image setting and refactor activity logic
  websites/W/WeTV/metadata.json
  websites/W/WeTV/presence.ts
Labels: activity update

#9086 feat(AnimeLib): add support for 'messages' and 'downloads' cases
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9079 chore(AnimeLib): format metadata
  websites/A/AnimeLib/metadata.json
Labels: activity update, repo maintenance, chore

#9080 chore(Freek): update assets
  websites/F/Freek/metadata.json
  websites/F/Freek/presence.ts
Labels: activity update, repo maintenance, chore

#9095 chore(Sushi Scan): update assets
  websites/S/Sushi Scan/metadata.json
  websites/S/Sushi Scan/presence.ts
Labels: activity update, chore

#9096 chore(SOOP): update assets
  websites/S/SOOP/metadata.json
  websites/S/SOOP/presence.ts
Labels: activity update, chore

#9097 chore(WeTV): update assets
  websites/W/WeTV/metadata.json
  websites/W/WeTV/presence.ts
Labels: activity update, chore

#9078 chore: add conditional check for repository owner in Crowdin workflow
  .github/workflows/crowdin.yml
Labels: repo maintenance

#9093 feat(Apple TV+): rewrite activity
  websites/A/Apple TV+/metadata.json
  websites/A/Apple TV+/presence.ts
Labels: activity update

#9029 feat(Sflix): add presence
  websites/S/Sflix/iframe.ts
  websites/S/Sflix/metadata.json
  websites/S/Sflix/presence.ts
Labels: activity creation

#9083 feat(Desu-Online): update presence
  websites/D/Desu-Online/metadata.json
  websites/D/Desu-Online/presence.ts
Labels: activity update

#9100 feat(Watch-Anime): information update visible
  websites/W/Watch-Anime/metadata.json
  websites/W/Watch-Anime/presence.ts
Labels: activity update

#9087 feat(Cineby): add activity
  websites/C/Cineby/api.ts
  websites/C/Cineby/metadata.json
  websites/C/Cineby/presence.ts
Labels: activity creation

#9105 chore(YouTube Music): update various things
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9107 chore(SoundCloud): only show small image on pause
  websites/S/SoundCloud/metadata.json
  websites/S/SoundCloud/presence.ts
Labels: activity update

#9109 chore(PlanetXO): Removed unneeded metadata.
  websites/P/PlanetXO/metadata.json
Labels: activity update

#9111 chore(Sflix): update assets
  websites/S/Sflix/metadata.json
  websites/S/Sflix/presence.ts
Labels: activity update, repo maintenance, chore

#9115 chore(PlanetXO): format metadata
  websites/P/PlanetXO/metadata.json
Labels: activity update, repo maintenance, chore

#9116 chore(Cineby): update assets
  websites/C/Cineby/metadata.json
  websites/C/Cineby/presence.ts
Labels: activity update, repo maintenance, chore

#9110 fix(AnimeUnity): update outdated url
  websites/A/AnimeUnity/metadata.json
Labels: activity update

#9118 chore(AnimeUnity): format metadata
  websites/A/AnimeUnity/metadata.json
Labels: activity update, repo maintenance, chore

#9094 feat(Granblue Fantasy): add raid details & query only necessary data
  websites/G/Granblue Fantasy/metadata.json
  websites/G/Granblue Fantasy/presence.ts
Labels: activity update

#9119 feat(Freek): add more sources to iframe regex
  websites/F/Freek/metadata.json
Labels: activity update

#9120 feat(Trakt): display show and movie covers
  websites/T/Trakt/metadata.json
  websites/T/Trakt/presence.ts
Labels: activity update

#9117 fix(AnimeSaturn): update domain
  websites/A/AnimeSaturn/metadata.json
Labels: activity update

#9121 chore(Granblue Fantasy): update assets
  websites/G/Granblue Fantasy/metadata.json
  websites/G/Granblue Fantasy/presence.ts
Labels: activity update, chore

#9122 chore(AnimeSaturn): format metadata
  websites/A/AnimeSaturn/metadata.json
Labels: activity update, chore

#9124 chore(PCGamingWiki): update assets
  websites/P/PCGamingWiki/metadata.json
  websites/P/PCGamingWiki/presence.ts
Labels: activity update, chore

#9129 chore(Google Play): remove regExp
  websites/G/Google Play/metadata.json
Labels: activity update

#9128 fix(Granblue Fantasy): handle no alive boss
  websites/G/Granblue Fantasy/metadata.json
  websites/G/Granblue Fantasy/presence.ts
Labels: activity update

#9126 feat(ArcViewer): add timebar and fixes
  websites/A/ArcViewer/metadata.json
  websites/A/ArcViewer/presence.ts
Labels: activity update

#9102 feat(U-NEXT): add activity
  websites/U/U-NEXT/U-NEXT.json
  websites/U/U-NEXT/functions/fetchLiveMetadata.ts
  websites/U/U-NEXT/functions/fetchMetadata.ts
  websites/U/U-NEXT/metadata.json
  websites/U/U-NEXT/package-lock.json
  websites/U/U-NEXT/package.json
  websites/U/U-NEXT/presence.ts
  websites/U/U-NEXT/types.ts
Labels: activity creation

#9125 chore(PlanetXO): Added Player Support
  websites/P/PlanetXO/metadata.json
  websites/P/PlanetXO/presence.ts
Labels: activity update

#9130 chore(U-NEXT): update assets
  websites/U/U-NEXT/metadata.json
  websites/U/U-NEXT/presence.ts
Labels: activity update, repo maintenance, chore

#9131 fix(Prime Video): change regex
  websites/P/Prime Video/metadata.json
Labels: activity update

#9133 chore(PlanetXO): format metadata
  websites/P/PlanetXO/metadata.json
Labels: activity update, repo maintenance, chore

#9141 chore: delete DMCA'd activities
  websites/H/HiAnime/iframe.ts
  websites/H/HiAnime/metadata.json
  websites/H/HiAnime/presence.ts
  websites/S/StreamEast/metadata.json
  websites/S/StreamEast/presence.ts
Labels: activity deletion

#9136 chore(Prime Video): format metadata
  websites/P/Prime Video/metadata.json
Labels: activity update, repo maintenance, chore

#9137 chore(MoviesJoy): format metadata
  websites/M/MoviesJoy/metadata.json
Labels: activity update, repo maintenance, chore

#9140 chore(Granblue Fantasy): remove `largeImageText` & fix getting boss hp
  websites/G/Granblue Fantasy/metadata.json
  websites/G/Granblue Fantasy/presence.ts
Labels: activity update

#9138 feat(types): allow setting largeImageKey for listening activites
  @types/premid/index.d.ts
Labels: repo maintenance

#9134 feat(DEX Screener): add presence
  websites/D/DEX Screener/metadata.json
  websites/D/DEX Screener/presence.ts
Labels: activity creation

#9139 feat(Claude): add activity
  websites/C/Claude/Claude.json
  websites/C/Claude/metadata.json
  websites/C/Claude/package-lock.json
  websites/C/Claude/package.json
  websites/C/Claude/presence.ts
Labels: activity creation

#9148 chore: update activities
  @types/premid/index.d.ts
  websites/D/Disney+/metadata.json
  websites/D/Disney+/presence.ts
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update, multiple activities

#9151 chore(DEX Screener): update assets
  websites/D/DEX Screener/metadata.json
  websites/D/DEX Screener/presence.ts
Labels: activity update, chore

#9157 feat(Granblue Fantasy): style character image
  websites/G/Granblue Fantasy/metadata.json
  websites/G/Granblue Fantasy/presence.ts
Labels: activity update

#9158 feat(Phira): add activity
  websites/P/Phira/metadata.json
  websites/P/Phira/presence.ts
Labels: activity creation

#9154 chore(Netflix): update version to 6.2.0 & implement season logic
  websites/N/Netflix/metadata.json
  websites/N/Netflix/presence.ts
Labels: activity update

#9162 chore(Claude): update assets
  websites/C/Claude/metadata.json
  websites/C/Claude/presence.ts
Labels: activity update, repo maintenance, chore

#9163 chore(Phira): update assets
  websites/P/Phira/metadata.json
  websites/P/Phira/presence.ts
Labels: activity update, repo maintenance, chore

#9147 feat(PikiDiary): add activity
  websites/P/PikiDiary/metadata.json
  websites/P/PikiDiary/presence.ts
Labels: activity creation

#9150 feat(Freek): implement season and episode text through largeImageText
  websites/F/Freek/metadata.json
  websites/F/Freek/presence.ts
Labels: activity update

#9156 feat(YouTube Music): utilize `largeImageText` for albums
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9155 feat(Timeguessr): add activity
  websites/T/Timeguessr/metadata.json
  websites/T/Timeguessr/presence.ts
Labels: activity creation

#9169 chore(PikiDiary): update assets
  websites/P/PikiDiary/metadata.json
  websites/P/PikiDiary/presence.ts
Labels: activity update, repo maintenance, chore

#9159 feat(Eurogamer): add activity
  websites/E/Eurogamer/metadata.json
  websites/E/Eurogamer/presence.ts
Labels: activity creation

#9165 chore(AnimeLib): cache current dub
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9176 fix(YouTube Music): only set largeImageText when needed
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9173 chore(Timeguessr): update assets
  websites/T/Timeguessr/metadata.json
  websites/T/Timeguessr/presence.ts
Labels: activity update, chore

#9175 feat: send i18n file to extension in dev mode
  cli/bin/actions/modify.js
  cli/src/actions/modify.ts
Labels: repo maintenance

#9174 chore(AnimeLib): format metadata
  websites/A/AnimeLib/metadata.json
Labels: activity update, repo maintenance, chore

#9166 feat(Brave Search): use strings
  websites/B/Brave Search/Brave Search.json
  websites/B/Brave Search/metadata.json
  websites/B/Brave Search/presence.ts
Labels: activity update

#9178 chore(Tsuki Mangás): delete activity
  websites/T/Tsuki Mangás/metadata.json
  websites/T/Tsuki Mangás/presence.ts
Labels: activity deletion

#9185 fix: check if there is an i18n file and restart on add/unlink
  cli/bin/actions/modify.js
  cli/src/actions/modify.ts
Labels: repo maintenance

#9188 refactor: remove Subso, the useless web
  websites/S/Subso/metadata.json
  websites/S/Subso/presence.ts
  websites/T/The useless web/metadata.json
  websites/T/The useless web/presence.ts
Labels: activity deletion, multiple activities

#9187 feat(tranimeizle): change website url
  websites/T/TRanimeizle/metadata.json
Labels: activity update

#9194 chore: adding www in metadata
  websites/R/RadiosNet/metadata.json
Labels: activity update

#9202 feat(Viu): update activity type
  websites/V/Viu/metadata.json
  websites/V/Viu/presence.ts
Labels: activity update

#9183 feat(kisskh): add activity
  websites/K/kisskh/metadata.json
  websites/K/kisskh/presence.ts
Labels: activity creation

#9198 refactor(Hyakanime): refactored code and update some routes
  websites/H/Hyakanime/metadata.json
  websites/H/Hyakanime/presence.ts
Labels: activity update

#9181 feat(Pi Fansubs): add activity
  websites/P/Pi Fansubs/iframe.ts
  websites/P/Pi Fansubs/metadata.json
  websites/P/Pi Fansubs/presence.ts
Labels: activity creation

#9214 fix(YT:M): support for audio-only playback
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9213 refactor(Jackbox): enable mobile flag
  websites/J/Jackbox/metadata.json
Labels: activity update

#9210 chore(kisskh): update assets
  websites/K/kisskh/metadata.json
  websites/K/kisskh/presence.ts
Labels: activity update, repo maintenance, chore

#9215 chore(Eurogamer): update assets
  websites/E/Eurogamer/metadata.json
  websites/E/Eurogamer/presence.ts
Labels: activity update, repo maintenance, chore

#9201 feat(ChatGPT): add multilanguage & option to change logo
  websites/C/ChatGPT/ChatGPT.json
  websites/C/ChatGPT/metadata.json
  websites/C/ChatGPT/presence.ts
  websites/C/Claude/Claude.json
Labels: activity update

#9217 chore(Pi Fansubs): update assets
  websites/P/Pi Fansubs/metadata.json
  websites/P/Pi Fansubs/presence.ts
Labels: activity update, repo maintenance, chore

#9207 fix(Dropout): update url
  websites/D/Dropout/metadata.json
Labels: activity update

#9223 chore: update metadata sorter
  tools/classes/PresenceCompiler.ts
  tools/metadataSorter.ts
Labels: repo maintenance, chore

#9225 chore: format metadata
  websites/D/Dropout/metadata.json
  websites/J/Jackbox/metadata.json
  websites/Y/YouTube/metadata.json
Labels: activity update, multiple activities, repo maintenance, chore

#9221 chore(ChatGPT): update assets
  websites/C/ChatGPT/metadata.json
  websites/C/ChatGPT/presence.ts
Labels: activity update, repo maintenance, chore

#9189 fix(Anghami): add cover and timestamps
  websites/A/Anghami/metadata.json
  websites/A/Anghami/presence.ts
Labels: activity update

#9191 feat(paramount+): convert to watching activity
  websites/P/Paramount+/metadata.json
  websites/P/Paramount+/presence.ts
Labels: activity update

#9209 feat(Emby): add more settings, fix issues & takeover activity
  websites/E/Emby/metadata.json
  websites/E/Emby/presence.ts
Labels: activity update
