Repository PreMiD/Activities, pull requests merged in 2025-07, with the labels that each got.

#9710 feat(The Church of Jesus Christ of Latter-day Saints): add activity
  websites/T/The Church of Jesus Christ of Latter-day Saints/metadata.json
  websites/T/The Church of Jesus Christ of Latter-day Saints/presence.ts
Labels: inactive, activity creation

#9732 feat(AlternativeScans): add activity
  websites/A/AlternativeScans/metadata.json
  websites/A/AlternativeScans/presence.ts
Labels: activity creation

#9750 feat(Tsukime): add activity
  websites/T/Tsukime/metadata.json
  websites/T/Tsukime/presence.ts
Labels: activity creation

#9751 feat(Blooket): updated mode support
  websites/B/Blooket/metadata.json
  websites/B/Blooket/presence.ts
Labels: activity update

#9752 fix(Vizer): update domain
  websites/V/Vizer/metadata.json
Labels: activity update

#9753 fix(AniKenji Movie): Fix Buttons
  websites/A/AniKenji Movie/metadata.json
  websites/A/AniKenji Movie/presence.ts
Labels: activity update

#9761 fix(osu!ppy): fix multilanguage strings
  websites/O/osu ppy/metadata.json
  websites/O/osu ppy/osu!ppy.json
  websites/O/osu ppy/presence.ts
Labels: activity update

#9742 feat(巴哈姆特動畫瘋): update activity image and details
  websites/#/巴哈姆特動畫瘋/metadata.json
  websites/#/巴哈姆特動畫瘋/presence.ts
Labels: activity update

#9747 feat(KOLEO): update presence
  websites/K/KOLEO/metadata.json
  websites/K/KOLEO/presence.ts
Labels: activity update

#9775 feat(HBO Max): add presence and remove the old Max
  websites/H/HBO Max/metadata.json
  websites/H/HBO Max/presence.ts
Labels: activity creation

#9779 feat(movie-web): new pstream domain
  websites/M/movie-web/metadata.json
Labels: activity update

#9791 feat: add StatusDisplayType enum and update PresenceOptions with new fields
  @types/premid/index.d.ts
Labels: repo maintenance

#9780 feat(ManwhaWeb): add activity
  websites/M/ManhwaWeb/metadata.json
  websites/M/ManhwaWeb/presence.ts
Labels: activity creation

#9803 fix(Twitch): fix streamer title in mod view
  websites/T/Twitch/metadata.json
  websites/T/Twitch/presence.ts
Labels: activity update

#9790 feat(Taobao): add activity
  websites/T/Taobao/metadata.json
  websites/T/Taobao/presence.ts
Labels: activity creation

#9783 feat(OpenFront.io): add activity
  websites/O/OpenFront.io/metadata.json
  websites/O/OpenFront.io/presence.ts
Labels: activity creation

#9801 feat(WatchPeopleLive): add activity
  websites/W/WatchPeopleLive/metadata.json
  websites/W/WatchPeopleLive/presence.ts
Labels: activity creation

#9813 feat(Sflix): update activity
  websites/S/Sflix/iframe.ts
  websites/S/Sflix/metadata.json
  websites/S/Sflix/presence.ts
Labels: activity update

#9811 feat(anilife): add activity
  websites/A/anilife/metadata.json
  websites/A/anilife/presence.ts
Labels: activity creation

#9806 feat(Mangafire): add activity
  websites/M/Mangafire/metadata.json
  websites/M/Mangafire/presence.ts
Labels: activity creation

#9816 fix(Youtube Music): fix artist being duplicated
  websites/Y/YouTube Music/metadata.json
  websites/Y/YouTube Music/presence.ts
Labels: activity update

#9810 feat(pwn.college): add activity
  websites/P/pwn.college/metadata.json
  websites/P/pwn.college/presence.ts
Labels: activity creation

#9819 feat(Hdfilmcehennemi): add activity
  websites/H/Hdfilmcehennemi/iframe.ts
  websites/H/Hdfilmcehennemi/metadata.json
  websites/H/Hdfilmcehennemi/presence.ts
Labels: activity creation

#9827 feat(Watch-Anime): update activity
  websites/W/Watch-Anime/metadata.json
  websites/W/Watch-Anime/presence.ts
Labels: activity update
