Repository PreMiD/Activities, pull requests merged in 2025-02, with the labels that each got.

#9278 feat: add deprecation rule
  @types/premid/index.d.ts
  eslint.config.mjs
  premid/src/functions/getTimestamps.ts
  premid/src/functions/getTimestampsFromMedia.ts
  premid/src/functions/timestampFromFormat.ts
  premid/src/index.ts
Labels: repo maintenance

#9276 fix(update-assets): run on push instead of pr
  .github/workflows/assets-updater.yml
  cli/src/classes/AssetsManager.test.ts
  cli/src/classes/AssetsManager.ts
  cli/src/commands/updateAssets.ts
  cli/src/util/log.ts
Labels: repo maintenance

#9232 feat(NovaStream): add activity
  websites/N/NovaStream/metadata.json
  websites/N/NovaStream/presence.ts
Labels: activity creation

#9256 fix(Kodi): updated client ID and readme
  websites/K/Kodi/metadata.json
  websites/K/Kodi/presence.ts
  websites/K/Kodi/readme.md
Labels: activity update

#9227 feat(Leboncoin): fix and improve pratically everything
  websites/L/Leboncoin/metadata.json
  websites/L/Leboncoin/presence.ts
Labels: activity update

#9265 fix(Disney+): fixes not working when 1.00 image not available
  websites/D/Disney+/metadata.json
  websites/D/Disney+/presence.ts
Labels: activity update

#9259 feat(bilibili): add episode support and fix article bug
  websites/B/bilibili/presence.ts
Labels: activity update

#9249 feat(VLC): Add support for "Watching" and "Listening" statuses and add Album art as largeImageKey.
  websites/V/VLC/metadata.json
  websites/V/VLC/presence.ts
Labels: activity update

#9253 feat(Envolya): add activity
  websites/E/Envolya/metadata.json
  websites/E/Envolya/presence.ts
Labels: activity creation

#9270 fix(Plex): fix it showing listening when watching
  websites/P/Plex/metadata.json
  websites/P/Plex/presence.ts
Labels: activity update

#9275 feat(Rhythm+): add activity
  websites/R/Rhythm+/metadata.json
  websites/R/Rhythm+/presence.ts
Labels: activity creation

#9307 feat(validator): add tags check
  cli/src/classes/ActivityCompiler.ts
  cli/src/util/getActivities.ts
  cli/src/util/sarif.ts
  websites/G/Game8/metadata.json
  websites/T/Town of Salem/metadata.json
  websites/U/Uncyclopedia/metadata.json
  websites/W/WriterDuet/metadata.json
Labels: activity update, multiple activities, repo maintenance

#9311 chore: improve GitHub workflow file names
  .github/workflows/assets-updater.yml
  .github/workflows/pmd.yml
  .github/workflows/release.yml
Labels: repo maintenance

#9284 feat(movie-web): update urls
  websites/M/movie-web/metadata.json
Labels: activity update

#9286 chore: update nickname in my contributions
  websites/C/cda.pl/metadata.json
  websites/F/filman.cc/metadata.json
  websites/M/Musixmatch/metadata.json
  websites/T/Trakt/metadata.json
Labels: activity update, multiple activities, chore

#9289 fix(Google): fix querySelector & update deprecated attribute & add showSmallImages setting
  websites/G/Google/metadata.json
  websites/G/Google/presence.ts
Labels: activity update

#9293 feat(BetterAnime): show title as activity & cover art
  websites/B/BetterAnime/metadata.json
  websites/B/BetterAnime/presence.ts
Labels: activity update

#9294 fix(Anime Sama): fix homepage that was no longer recognized
  websites/A/Anime Sama/metadata.json
  websites/A/Anime Sama/presence.ts
Labels: activity update

#9295 chore(Claude): suppresion of paranthesis not necessary
  websites/C/Claude/Claude.json
Labels: activity update

#9300 fix(Discord Extreme List): update author info and URLs
  websites/D/Discord Extreme List/metadata.json
Labels: activity update

#9251 feat(Club Penguin Journey): Add support for current RoomId with Room display on Status.
  websites/C/Club Penguin Journey/metadata.json
  websites/C/Club Penguin Journey/presence.ts
Labels: activity update

#9274 feat(Baekjoon Online Judge): add activity
  websites/B/Baekjoon Online Judge/metadata.json
  websites/B/Baekjoon Online Judge/presence.ts
Labels: activity creation

#9282 feat(Framer): add activity
  websites/F/Framer/metadata.json
  websites/F/Framer/presence.ts
Labels: activity creation

#9272 feat(AnimeciX): Add new presence
  websites/A/AnimeciX/metadata.json
  websites/A/AnimeciX/presence.ts
Labels: activity creation

#9292 chore(AnimeLib): settings in native language
  websites/A/AnimeLib/metadata.json
  websites/A/AnimeLib/presence.ts
Labels: activity update

#9273 fix(LITT Live): add www subdomain
  websites/L/LITT Live/metadata.json
Labels: activity update

#9322 feat(AnimeciX): Update metadata new domain
  websites/A/AnimeciX/metadata.json
Labels: activity update

#9264 feat(AniTilky): add activity
  websites/A/AniTilky/metadata.json
  websites/A/AniTilky/presence.ts
Labels: activity creation

#9271 feat(Le Chat): Add new presence
  websites/L/Le Chat/Le Chat.json
  websites/L/Le Chat/metadata.json
  websites/L/Le Chat/presence.ts
Labels: activity creation

#9296 feat(AnimeGo): add mirror url
  websites/A/AnimeGO/metadata.json
Labels: activity update

#9299 feat(AnimeKai): Add presence
  websites/A/AnimeKai/iframe.ts
  websites/A/AnimeKai/metadata.json
  websites/A/AnimeKai/presence.ts
Labels: activity creation

#9301 feat(JSR): add JSR presence
  websites/J/JSR/metadata.json
  websites/J/JSR/presence.ts
Labels: activity creation

#9303 feat(bilibili): Add support for live streaming of matches
  websites/B/bilibili/iframe.ts
  websites/B/bilibili/metadata.json
  websites/B/bilibili/presence.ts
Labels: activity update

#9332 chore: delete DMCA'd websites
  websites/K/kisskh/metadata.json
  websites/K/kisskh/presence.ts
  websites/M/MangaKakalot/metadata.json
  websites/M/MangaKakalot/presence.ts
  websites/M/Miruro/metadata.json
  websites/M/Miruro/presence.ts
  websites/P/p90.zone/metadata.json
  websites/P/p90.zone/presence.ts
Labels: activity deletion, multiple activities, chore

#9335 chore(Deno): keep functions updated
  websites/D/Deno/metadata.json
  websites/D/Deno/presence.ts
Labels: activity update

#9316 fix(bilibili): Fix bug
  websites/B/bilibili/metadata.json
  websites/B/bilibili/presence.ts
Labels: activity update

#9327 feat(e-typing): add e-typing presence
  websites/E/e-typing/metadata.json
  websites/E/e-typing/presence.ts
Labels: activity creation

#9328 feat(Vinted): add activity
  websites/V/Vinted/metadata.json
  websites/V/Vinted/presence.ts
Labels: activity creation

#9331 feat(Anizium): Add new presence
  websites/A/Anizium/iframe.ts
  websites/A/Anizium/metadata.json
  websites/A/Anizium/presence.ts
Labels: activity creation

#9337 feat(Cyfrin Updraft): add Cyfrin Updraft presence
  websites/C/Cyfrin Updraft/metadata.json
  websites/C/Cyfrin Updraft/presence.ts
Labels: activity creation

#9338 feat(Jackbox): add The Jackbox Survey Scramble
  websites/J/Jackbox/games/Non-Pack/bigsurvey.ts
  websites/J/Jackbox/games/index.ts
  websites/J/Jackbox/presence.ts
  websites/J/Jackbox/types.ts
Labels: activity update

#9341 chore(NPM Package Registry): fix info of non-exist pacakge
  websites/N/NPM Package Registry/metadata.json
  websites/N/NPM Package Registry/presence.ts
Labels: activity update

#9342 fix(VLC): revert breaking change from #4946 & fix deprecated & fix Type
  websites/V/VLC/metadata.json
  websites/V/VLC/presence.ts
Labels: activity update

#9343 refactor(BBC): import getTimestamps and fix strings being undefined
  websites/B/BBC/metadata.json
  websites/B/BBC/presence.ts
Labels: activity update

#9323 feat(YTyping): add YTyping presence
  websites/Y/YTyping/iframe.ts
  websites/Y/YTyping/metadata.json
  websites/Y/YTyping/presence.ts
Labels: activity creation

#9340 chore(cli): fix punycode deprecation warning
  cli/package-lock.json
  cli/package.json
Labels: dependencies, repo maintenance

#9344 fix(Twitch): popup chat no longer shows default status
  websites/T/Twitch/metadata.json
  websites/T/Twitch/presence.ts
Labels: activity update

#9345 docs: update README with comprehensive developmend guide
  .github/PULL_REQUEST_TEMPLATE.MD
  README.md
  cli/src/commands/release.ts
  cli/src/commands/updateAssets.ts
  cli/src/util/log.ts
  package.json
Labels: repo maintenance
